[build]
target = "x86_64-unknown-uefi"

[target.'cfg(all())']
rustflags = [
  "-Wfuture_incompatible",
  "-Wnonstandard_style",
  "-Wrust_2018_compatibility",
  "-Wrust_2018_idioms",
  "-Wrust_2021_compatibility",
  "-Wmeta_variable_misuse",
  "-Wmissing_abi",
  "-Wmissing_debug_implementations",
  "-Wnon_ascii_idents",
  "-Wnoop_method_call",
  "-Wsingle_use_lifetimes",
  "-Wtrivial_numeric_casts",
  "-Wunreachable_pub",
  "-Wunsafe_op_in_unsafe_fn",
  "-Wunused_crate_dependencies",
  "-Wunused_import_braces",
  "-Wunused_macro_rules",
  "-Wunused_qualifications",
  "-Wvariant_size_differences",
  "-Wclippy::all",
  "-Wclippy::pedantic",
  "-Wclippy::clone_on_ref_ptr",
  "-Wclippy::decimal_literal_representation",
  "-Wclippy::default_union_representation",
  "-Wclippy::empty_structs_with_brackets",
  "-Wclippy::inline_asm_x86_att_syntax",
  "-Wclippy::rc_buffer",
  "-Wclippy::rest_pat_in_fully_bound_structs",
  "-Wclippy::same_name_method",
  "-Wclippy::string_slice",
  "-Wclippy::string_to_string",
  "-Wclippy::str_to_string",
  "-Wclippy::undocumented_unsafe_blocks",
  "-Wclippy::unneeded_field_pattern",
  "-Wclippy::unreachable",
  "-Wclippy::unwrap_used",
  "-Wrustdoc::broken_intra_doc_links",
  "-Wrustdoc::private_intra_doc_links",
  "-Wrustdoc::invalid_codeblock_attributes",
  "-Wrustdoc::invalid_rust_codeblocks",
  "-Wrustdoc::bare_urls",
  "-Aclippy::cast_possible_truncation",
]
